-- Drop any existing data.

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS list;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS completed;
DROP TABLE IF EXISTS seq;
DROP VIEW IF EXISTS lists;
DROP VIEW IF EXISTS tasks;
DROP PROCEDURE IF EXISTS completed_task;
DROP TRIGGER IF EXISTS add_user;
DROP TRIGGER IF EXISTS add_seq;
DROP TRIGGER IF EXISTS reorder;
