-- Drop any existing data.

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS list;
DROP TABLE IF EXISTS list_seq;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS task_seq;
DROP TABLE IF EXISTS completed;
DROP VIEW IF EXISTS lists;
DROP VIEW IF EXISTS tasks;
DROP VIEW IF EXISTS completeds;
DROP PROCEDURE IF EXISTS complete_task;
DROP PROCEDURE IF EXISTS revert_completed;
DROP TRIGGER IF EXISTS add_user;
DROP TRIGGER IF EXISTS add_list_seq;
DROP TRIGGER IF EXISTS add_task_seq;
DROP TRIGGER IF EXISTS reorder_list;
DROP TRIGGER IF EXISTS reorder_task;
